### ISSUE TITLE
Web example does not work

### ISSUE THREAD

**Issue by olehbozhok** [ArthurBrussee/brush#12]
![image](https://github.com/user-attachments/assets/0bc37c00-c2bc-4986-b2d9-e8ac26cd8ed5)

**Comment by ArthurBrussee** [comment]
Woops messed up the version last push, I just pushed another version that should work, can you give it a go? Thank you!

**Comment by olehbozhok** [comment]
Thanks for quick answer
Still see the problem
![image](https://github.com/user-attachments/assets/babf6bb7-e48c-446c-9d2b-fc69f04e61fd)

**Comment by ArthurBrussee** [comment]
Ah ok but that's a different error now! That seems like WebGPU isn't supported :/

I haven't tested on Brave - I think it still requires some flags to enable WebGPU. Additionally, the website requires a Chrome origin trial, so Brave might not like that. On chrome that's enabled with `[enable-unsafe-webgpu](chrome://flags/#enable-unsafe-webgpu)`

You can try out whether WebGPU works here: https://webgpu.github.io/webgpu-samples/?sample=texturedCube

**Comment by olehbozhok** [comment]
https://webgpu.github.io/webgpu-samples/?sample=texturedCube
it works

and egui works https://emilk.github.io/ehttp/index.html

**Comment by olehbozhok** [comment]
And your web app also works now =)

**Comment by ArthurBrussee** [comment]
Ahh ok phew :D Maybe was just some cache not clearning then. Closing this but do lmk if it breaks again / other issues, thanks!
